name: Cypress Tests

on: 
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    - cron: '* 6 * * *' 
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Cypress run
        uses: cypress-io/github-action@v2.9.7
        with:
          browser: chrome
          parallel: true
          record: true
          group: Cypress Dashboard
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      

